### ISSUE TITLE
Override components hidden when iframed

### ISSUE THREAD

**Issue by louh** [mapzen/ui#29]
Search and locate-me are automatically hidden when we're in an iframe. Sometimes this is not desirable, e.g. when embedded into a blog post or page where the demo requires interaction. (See Indy's "Where the streets have no name.") Let's preserve the current assumption for the drop-in use case, but provide a way to override this behavior. (Idea: option `{ forceDisplay: true }`)

**Comment by louh** [comment]
cc @meetar Is this the thing you were planning to work on for @IndyHurt ? I think I might have forgotten this issue was opened.

**Comment by meetar** [comment]
Yep! I was looking at this yesterday, trying to figure out how to pass
options to the other components. I assume I'll need to export them as
self-instantiating modules, the way the bug is now?

**Comment by louh** [comment]
This issue was moved to mapzen/scarab#5
