### ISSUE TITLE
Attribution "bug" design document

### ISSUE THREAD

**Issue by louh** [mapzen/ui#4]
_Work in progress._

### Overview

We make demo pages that are [meant to be iframed into other pages](https://tangrams.github.io/tangram/#mapzen,40.70532700869127,-74.0097749233246,16). [Sometimes](http://tangrams.github.io/tangram-docs-assets/?procedural/tronish.yaml#16/40.7053/-74.0098) they [go viral](http://www.citylab.com/design/2015/03/a-mesmerizing-futuristic-map-with-animated-traffic-and-glowing-buildings/388285/). When this happens, the demo map is often linked to directly, and most viewers have no way of coming back to a Mapzen page to learn more. We need a way to brand demo pages when viewed out of context.

The term "bug" used here is borrowed from broadcast television (officially, ["digital on-screen graphic"](http://en.wikipedia.org/wiki/Digital_on-screen_graphic)) where a show is branded in the lower corner to identify the broadcast network. The other meaning of "bug" in computing might make this not a great term to use in the long run.

The main goals for the bug:

1. Identify that the demo is powered by Mapzen and provide a link back to us (or the product page, etc.)
2. Provide a way to easily share via social networks to drive up each demo's viral capacity.

### Design mockups

1. Square corners, social icons highlight with underline (closer to navbar of current site)

    ![bug01](https://cloud.githubusercontent.com/assets/2553268/7455735/b30fde02-f24c-11e4-9c5e-f5fdaa2faf7b.png)

2. Alternate: rounded corners, social icons inside circles (more generic)

    ![bug02](https://cloud.githubusercontent.com/assets/2553268/7455734/b30a4f64-f24c-11e4-8af6-a716d58f6c6b.png)

These mockups show intent, they are not meant to be pixel perfect representations.

There will only be one canonical "official" stylesheet. Custom CSS to override the preset styles are available if you really want to.

### Implementation

The "bug" is designed as a standalone, drop-in JavaScript "library". It has no other hard dependencies (jQuery is not required) and should work on modern browsers and IE9+ at minimum, although in practice compatibility would be largely driven by the demo itself. Since it is served from the [RawGit CDN](https://rawgit.com/), updates to the bug can propagate to all demo pages that use it. (There is a cache time on RawGit. You can [refer to commits directly](https://rawgit.com/faq) instead of the master branch to lock the bug to a specific version, but this means you'll need to manually upgrade it in the future.)

```html
<!-- Mapzen bug UI component -->
<script src='https://cdn.rawgit.com/mapzen/ui/0.1.1/components/bug/bug.js'></script>
```

Instantiate the bug:
```js
var mzBug = new MapzenBug();
```

You pay pass in an optional object with options:

```js
var mzBug = new MapzenBug({
  name: 'Tangram',
  link: 'https://github.com/tangrams/tangram/',
  tweet: 'Wow, what a cool demo by @mapzen!'
});
```

All options are optional. Defaults will be provided if not set.

key | default value | description
---|---|---
__link__ | 'https://mapzen.com/' | _String._ URL to go to when viewer clicks on the Mapzen logo. This should be a valid absolute URL.
__name__ | 'Mapzen demo' | _String._ Name of the demo or product. This will be used in analytics tracking.
__analytics__ | true | _Boolean._ Whether to send custom tracking events to Google Analytics for this demo. Set to false to prevent this demo from sending custom events even if GA is present (but GA will still track page views and other default behavior that is not part of the bug functionality).
__tweet__ | (depends) | _String._ Set a custom pre-written tweet message. The current URL of the page will be automatically appended to the end of the message. If not included, a default tweet (based on the _name_ option, if provided) will be used.

#### Automatic iframe detection

The bug detects if the page being viewed is in an iframe or not. If it is in an iframe, it naively assumes that its parent page is giving the demo proper context, so its script stops executing immediately and does nothing else.

#### Google Analytics event tracking

If Google Analytics is detected on the page, the bug will send [custom tracking events](https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuide) to it.

If Google Analytics is not detected on the page, the bug will insert Mapzen's default Analytics code which will report back to the Mapzen website analytics property. This detection occurs some amount of milliseconds after the page is done loading to allow other Analytics code, if present, to load first.

The following events are tracked:

- The bug is active (that is, the viewer has opened this page outside of an iframe)
- If the bug is loading its own Analytics property 
- The viewer has clicked the Mapzen logo (which opens the URL)
- The viewer has clicked the Twitter icon
- The viewer has clicked the Facebook icon

_More info TBD_

#### Custom styling

Styling is provided either via DOM scripting or an external stylesheet (actual implementation TBD). DOM scripting means an external file won't need to be loaded (so it's slightly faster). An external stylesheet will be easier to override with custom styles, and is easier and more flexible to maintain, but requires an additional HTTP request.

Class names are provided to DOM elements generated by the bug script, prefixed in the `mz-bug-*` namespace. Custom styles overriding the bug styles should be generally discouraged as much as possible because there's no guarantee that class names or styles will be backwards-compatible forever. -- but because someone is bound to ask, yes, it is possible to override the styles.

#### Twitter (phase 1)

Twitter functionality should be similar to how it works on the [blog](https://mapzen.com/blog/) (via [RRSSB](https://github.com/kni-labs/rrssb)).

You may specify what the pre-filled tweet message is with the **tweet** option. If you don't set it, the default values are:

- If the **name** option is set, the pre-filled tweet is "_name_, powered by @mapzen"
- If the **name** option is _not_ set, the pre-filled tweet is "Check out this demo by @mapzen!"

All tweets will also automatically include the current URL of the page.

#### Facebook (phase 2)

Facebook functionality should be similar to how it works on the [blog](https://mapzen.com/blog/) (via [RRSSB](https://github.com/kni-labs/rrssb)).

#### Other sharing options (phase 3)

Other sharing options may be added in the future.

**Comment by souperneon** [comment]
@louh square please (no rounded corners for us at this time!) I'd like to play with the interaction a little bit to get a better feel

**Comment by louh** [comment]
:+1: square corners it is.

**Comment by louh** [comment]
@souperneon UI as of today: http://louhuang.com/simple-demo/#15/40.7364/-73.9751 (
