### ISSUE TITLE
Logo image size optimizations

### ISSUE THREAD

**Issue by louh** [mapzen/ui#8]
- Use actual size (better display on IE)
- Sprited (better hover state)

**Comment by souperneon** [comment]
![screen shot 2015-05-07 at 12 02 38 pm](https://cloud.githubusercontent.com/assets/6125224/7519892/fdf0ed74-f4b0-11e4-979f-86e4a0476d7e.png)

**Comment by louh** [comment]
New version of image is out, let's give that a try
